bug fix on win10_x86_64
bug fix: ValueError: Parent directory of model.ckpt doesn't exist, can't save.

error info:
    main_test_denoise_AE(model='sigmoid')       # model = relu, sigmoid
  File "D:/Users/Selay/Desktop/minst_test/tutorial_mnist.py", line 245, in main_test_denoise_AE
    save_path = saver.save(sess, "model.ckpt")
  File "D:\Explore\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1314, in save
    "Parent directory of {} doesn't exist, can't save.".format(save_path))
ValueError: Parent directory of model.ckpt doesn't exist, can't save.

platform info:
win10_x86_64
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]